--- # My First YAML playbook
- hosts: Test     
  user: root             
  connection: ssh
  gather_facts: no
  tasks:
    - name: Install HTTPD server on centos 7
      action: yum name=httpd state=installed

